'use strict';

/* Problem 2: Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1,2,3,5,8,13,21,34,55,89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 *
 * */

function fibo(maxVal) {
  const num     = [1,2];
  let   evenSum = 0;

  for (let i = 0; num[num.length - 1] < maxVal; i++) {
    num.push(num[i] + num[i + 1]);

    if ( !(num[i] % 2) ) {
      evenSum += num[i];
    }
  }

	console.log(num, evenSum);
	return `Even number sum: ${evenSum}`;
}

fibo(4000000);
